name: e4i2

on:
  push:
    branches:
      - main

jobs:
  E4is:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        options: >-
          --name mysql
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: e4i2
          MYSQL_USER: e4i2
          MYSQL_PASSWORD: 1234
        ports:
          - 3306:3306

    steps:
      - name: GitHub Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: application properties 파일 만들기
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: MySQL 권한 설정
        run: |
          container_id=$(docker ps -qf "ancestor=mysql:8.0")
          db_password="${{ secrets.DB_PASSWORD }}"
          docker exec $container_id mysql -uroot -p1234 -e "DROP USER IF EXISTS 'e4i2'@'%';"
          docker exec $container_id mysql -uroot -p1234 -e "CREATE USER 'e4i2'@'%' IDENTIFIED BY '1234';"
          docker exec $container_id mysql -uroot -p1234 -e "GRANT ALL PRIVILEGES ON e4i2.* TO 'e4i2'@'%'; FLUSH PRIVILEGES;"

      - name: gradle 권한 추가
        run: chmod +x gradlew

      - name: gradle 빌드
        env:
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: project.jar
          target: /root/E4I2_Server/tobe

      - name: SSH로 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            sudo systemctl restart mysql
            rm -rf /root/E4I2_Server/target
            mkdir /root/E4I2_Server/target
            mv /root/E4I2_Server/tobe/project.jar /root/E4I2_Server/target
            cd /root/E4I2_Server/target
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /root/E4I2_Server/tobe
